name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update appsettings
      uses: microsoft/variable-substitution@v1
      with:
        files: 'GraphPermissionParser/appsettings.json'
      env:
        ClientSecret: ${{ secrets.CLIENTSECRET }}    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o outbin
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Clone Microsoft Graph docs
      uses: actions/checkout@master
      with:
        repository: microsoftgraph/microsoft-graph-docs
        path: ./microsoft-graph-docs
    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx
    - name: Show Working directory
      run: tree
      shell: pwsh
    - name: Create Graph Permission Docs
      run: .\outbin\GraphPermissionParser "$(Get-Location)/microsoft-graph-docs/api-reference/v1.0/api" "$(Get-Location)\docfx_project"
      shell: pwsh
    - name: DocFX Build
      run: docfx .\docfx_project\docfx.json
    - name: Archive _site
      uses: actions/upload-artifact@v2
      with:
          name: _site
          path: docfx_project/_site

  deploy:
    runs-on: ubuntu-latest  
    needs: build
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _site
    - name: Show Working directory
      run: tree
      shell: pwsh          
    - name: Push to site report
      uses: selenehyun/gh-push@master
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        COMMIT_FILES: _site
        REPO_FULLNAME: merill/graphpermissions.github.io
        BRANCH: main
