name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 5,17 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update appsettings
      uses: microsoft/variable-substitution@v1
      with:
        files: 'GraphPermissionParser/appsettings.json'
      env:
        ClientSecret: ${{ secrets.CLIENTSECRET }}    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o outbin --configuration release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Clone Microsoft Graph docs
      uses: actions/checkout@master
      with:
        repository: microsoftgraph/microsoft-graph-docs
        path: ./d
    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx
    - name: Show Working directory
      run: tree
      shell: pwsh
    - name: Create Graph Permission Docs
      run: .\outbin\GraphPermissionParser "$(Get-Location)/d/api-reference" "$(Get-Location)\docfx_project"
      shell: pwsh
    - name: DocFX Build
      run: docfx .\docfx_project\docfx.json
    - name: Archive _site
      uses: actions/upload-artifact@v2
      with:
          name: _site
          path: docfx_project/_site

  deploy:
    runs-on: ubuntu-latest  
    needs: build
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site
    - name: Show Working directory
      run: tree
      shell: pwsh
    - name: Publish site to repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '_site/.'
        destination_repo: 'merill/graphpermissions.github.io'
        user_email: 'merill@merill.net'
        user_name: 'merill'
        commit_message: 'Automated Publish'
