name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update appsettings
      uses: microsoft/variable-substitution@v1
      with:
        files: 'GraphPermissionParser/appsettings.json'
      env:
        ClientSecret: ${{ secrets.CLIENTSECRET }}    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o outbin
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Clone Microsoft Graph docs
      uses: actions/checkout@master
      with:
        repository: microsoftgraph/microsoft-graph-docs
        path: ./microsoft-graph-docs
    - name: Show Working directory
      run: tree
      shell: pwsh
    - name: run permission parser
      run: ./GraphPermission/outbin/GraphPermissionParser.exe 
      shell: pwsh
