name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site
    - name: Show Working directory
      run: tree
      shell: pwsh
    - name: Publish site to repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '_site/*'
        destination_repo: 'merill/graphpermissions.github.io'
        user_email: 'merill@merill.net'
        user_name: 'merill'
        commit_message: 'Automated Publish'
